// Zoekbalk-autocomplete productdata — gedeeld door alle pagina's.
// Extern zodat Google deze productnamen niet als paginacontent leest op elke
// pagina die de zoekbalk heeft (zelfde reden als BouwRent's search-data.js —
// zie diens SEO-analyse 06/09/2026 over keyword-lek naar locatiepagina's).
var NAV_SEARCH_PRODUCTS = [
    { name: 'Partytent 4x8m', desc: 'Grote aluminium partytent voor tot 60 personen voor grote tuinfeesten.', link: 'partytent-4x8m.html', img: 'Pagodetent.png',
      keys: ['partytent','grote tent','pagodetent','feesttent','4x8','tent groot','tuinfeest tent'] },
    { name: 'Partytent 3x6m', desc: 'Stevige aluminium partytent voor tot 30 personen voor tuinfeesten in Gent.', link: 'partytent-3x6m.html', img: 'Pagodetent.png',
      keys: ['partytent','kleine tent','pagodetent','feesttent','3x6','tent klein','tuinfeest tent'] },
    { name: 'Rodeostier', desc: 'Elektrische rodeostier met opblaasbare valmat 5x5m voor feestjes en evenementen.', link: 'rodeostier.html', img: 'Rodeostier.png',
      keys: ['rodeo','rodeo stier','mechanische stier','bull ride','stier rijden'] },
    { name: 'Klaptafel 180cm', desc: 'Robuuste klaptafel voor 6-8 personen voor tuinfeesten in De Pinte.', link: 'klaptafel-180cm.html', img: 'Bankettafel.webp',
      keys: ['klaptafel','vouwtafel','feesttafel','tafel huren','bankettafel'] },
    { name: 'Barkruk Lounge Zwart', desc: 'Stijlvolle zwarte barkrukken voor recepties en lounge-setups in Oost-Vlaanderen.', link: 'barkruk.html', img: 'Barkruk lounge zwart.webp',
      keys: ['barkruk','barstoel','lounge kruk','receptie kruk'] },
    { name: 'Biertafelset', desc: 'Klassieke biertafelset met tafel en 2 banken voor casual tuinfeesten.', link: 'biertafelset.html', img: 'Eventrentals Logo.png',
      keys: ['biertafel','biertafelset','bierbank','tafel en banken'] },
    { name: 'Botsballen', desc: 'Opblaasbare botsballen voor lachgegarandeerd botsplezier op feestjes.', link: 'botsballen.html', img: 'Oplaasbare botsballen.jpg',
      keys: ['botsballen','sumo suits','bumperball','bodyzorb','zorb bal'] },
    { name: 'Buitenstoel', desc: 'Comfortabele terrasstoel voor tuinfeesten en evenementen in Oost-Vlaanderen.', link: 'buitenstoel.html', img: 'Buitenstoel.jpg',
      keys: ['buitenstoel','terrasstoel','tuinstoel'] },
    { name: 'Bungee Run', desc: 'Opblaasbare bungee run 8x3m voor twee deelnemers tegelijk op feestjes.', link: 'bungee-run.html', img: 'Bungeerun.png',
      keys: ['bungee run','bungeerun','trektouw spel','touwtrek attractie'] },
    { name: 'Easy-Up Vouwtent', desc: 'Snelspan vouwtent eenvoudig op te zetten voor tuinfeesten.', link: 'easy-up-vouwtent.html', img: 'Canopytent.png',
      keys: ['vouwtent','easy up','easyup','partytent klein','pop-up tent'] },
    { name: 'Hindernisbaan', desc: 'Uitdagende opblaasbare hindernisbaan 10x3m voor kinderfeestjes en evenementen.', link: 'hindernisbaan.html', img: 'Hindernissen.png',
      keys: ['hindernisbaan','obstacle course','hindernissen','opblaasbare hindernisbaan'] },
    { name: 'Houten Tentvloer', desc: 'Houten vloerplaten 1x2m voor onder de tent bij tuinfeesten.', link: 'houten-tentvloer.html', img: 'Plankenvloer.png',
      keys: ['tentvloer','vloer','houten vloer','vloerplaten'] },
    { name: 'Klapstoel Wit', desc: 'Elegante witte klapstoel voor tuinfeesten en evenementen in De Pinte en Gent.', link: 'klapstoel-wit.html', img: 'Vouwstoel.jpg',
      keys: ['klapstoel','vouwstoel','witte stoel','feeststoel'] },
    { name: 'Koelkast', desc: 'Elektrische koelkast voor dranken op het perfecte koude voor feestjes.', link: 'koelkast.html', img: 'Frigo.webp',
      keys: ['koelkast','frigo','drankkoeling','koeling huren'] },
    { name: 'LED Sfeerverlichting', desc: 'Set sfeervolle LED-lichtslinger voor tuinfeesten in De Pinte en Gent.', link: 'led-sfeerverlichting.html', img: 'feestverlichting.webp',
      keys: ['sfeerverlichting','led verlichting','lichtslinger','feestverlichting'] },
    { name: 'Muziekbox', desc: 'Draagbare Bluetooth-luidspreker met krachtig geluid voor buitenfeesten.', link: 'muziekbox.html', img: 'Eventrentals Logo.png',
      keys: ['muziekbox','speaker','luidspreker','bluetooth speaker','geluidsinstallatie'] },
    { name: 'Percolator', desc: 'Grote koffieketel voor 60-80 kopjes koffie voor recepties en feestjes.', link: 'percolator.html', img: 'Eventrentals Logo.png',
      keys: ['percolator','koffieketel','koffiezet','koffie voor groep'] },
    { name: 'Picknicktafel', desc: 'Stevige houten picknicktafel met geintegreerde banken voor 6-8 personen.', link: 'picknicktafel.html', img: 'Ronde bankettafel.webp',
      keys: ['picknicktafel','picknik tafel','houten tafel met banken'] },
    { name: 'Reuzespelen', desc: 'Set van 5 reuzespelen waaronder reuze-jenga en reuze-vier-op-een-rij voor alle leeftijden.', link: 'reuzespelen.html', img: 'Eventrentals Logo.png',
      keys: ['reuzespelen','reuze jenga','reuze vier op een rij','grote spelen'] },
    { name: 'Dino Springkasteel', desc: 'Groot opblaasbaar dino-springkasteel 6x5m met glijbaan voor kinderfeestjes.', link: 'springkasteel-groot-jungle.html', img: 'Springkasteel dino.png',
      keys: ['springkasteel','dino springkasteel','jungle springkasteel','groot springkasteel','springkasteel met glijbaan'] },
    { name: 'Springkasteel met Glijbaan', desc: 'Opblaasbaar springkasteel 5x5m met glijbaan voor kinderfeestjes.', link: 'springkasteel-medium-glijbaan.html', img: 'springkasteel met glijbaan.png',
      keys: ['springkasteel','springkasteel glijbaan','medium springkasteel'] },
    { name: 'Voetbal Darts', desc: 'Opblaasbaar voetbal-darts spel voor groepen en feesten in Oost-Vlaanderen.', link: 'springkasteel-piraat.html', img: 'Springkasteel darts.png',
      keys: ['voetbal darts','darts spel','voetbaldarts','opblaasbaar dartsspel'] },
    { name: 'Springkasteel Princess', desc: 'Roze prinsessen springkasteel 5x5m voor meisjesfeestjes in De Pinte.', link: 'springkasteel-princess.html', img: 'springkasteel princes.webp',
      keys: ['springkasteel','prinsessen springkasteel','roze springkasteel','meisjes springkasteel'] },
    { name: 'Standaard Springkasteel', desc: 'Klassiek opblaasbaar springkasteel 4x4m voor kinderfeestjes in Oost-Vlaanderen.', link: 'springkasteel-standaard.html', img: 'Standaard springkasteel.webp',
      keys: ['springkasteel','standaard springkasteel','klassiek springkasteel'] },
    { name: 'Statafel', desc: 'Stijlvolle statafel voor cocktailrecepties en staande diners in De Pinte en Gent.', link: 'statafel.html', img: 'Statafel.webp',
      keys: ['statafel','cocktailtafel','sta tafel','receptietafel'] },
    { name: 'Statafelhoes', desc: 'Witte stretch statafelhoes voor een nette afwerking van de statafel.', link: 'statafelhoes.html', img: 'Statafelhoes.webp',
      keys: ['statafelhoes','tafelhoes','statafel doek'] },
    { name: 'Tapinstallatie', desc: 'Complete bierinstallatie inclusief taptoren, bierkoel en CO₂ voor feesten in Oost-Vlaanderen.', link: 'tapinstallatie.html', img: 'Tapinstallatie.webp',
      keys: ['tapinstallatie','biertap','taptoren','bierinstallatie','fust tappen'] },
    { name: 'Terrasverwarmer', desc: 'Gasgedreven terrasverwarmer met paddenstoelkap voor buitenfeesten in De Pinte.', link: 'terrasverwarmer.html', img: 'verwarming op gas.webp',
      keys: ['terrasverwarmer','heater','gasverwarmer','paddenstoel verwarming'] },
];
